### PR TITLE
Feature/Tables listing for a Dataset

### PR DESCRIPTION
**Pull request by Eronne**
[comment]: [Status]()
[comment]: [Status]()

[Status]()

## Description
Add table listing for datasets.

## Todos
- [x] Convert components to TypeScript
- [x] Create listing view
- [x] Refacto components
- [x] The table name to show in the listing is the last part of the table full name (project:dataset.tablename)
- [x] Add a smaller query button
- [x] Add a search box to filter the tables
- [x] Add a refrech button to refresh the listing
- [x] Add chip to last update property
  - Lower than 26 hours, the Last Update Date is in a green Chip
  - Between than 26 hours and 36 hours, the Last Update Date is in a orange Chip
  - More than 36 hours, the Last Update Date is in a Red Chip
  - More than 49 hours, the Last Update Date is in a black Chip
- [x] For `numRows` & `numBytes` add a sparline chart + Value
- [x] Add a true / false "icon" for the Time partionning option.
- [x] By default, no tab in the table listing. Show the full list

## Deploy Notes
Review & merge

## Steps to Test or Reproduce
```sh
git checkout master
git pull
git checkout feature/tables-listing-for-dataset
```

1.  Navigate into data-models
2. Show listing page
3. Click on an Item

## Impacted Areas in Application
List general components of the application that this PR will affect:
- `src/components/data-models`
- `src/views/data-models`

### CODE REVIEW

**Comment by romone22** [comment]
Just some comments : 

- The table name to show in the listing is the last part of the table full name (project:dataset.tablename)
- Add a smaller query button
- Add a search box to filter the tables
- Add a refrech button to refresh the listing
- Add a true / false "icon" for the Time partionning option.
- By default, no tab in the table listing. Show the full list

I like the view :)

**Comment by Eronne** [comment]
@romone22 tell me if percents values for `v-progress-linear` are well defined in this PR :)

**Comment by romone22** [comment]
> @romone22 tell me if percents values for `v-progress-linear` are well defined in this PR :) 

@Eronne, the v-progress-linear seems Ok. I'm just wondering if we do not have to use a loggarythmic scale in place of a linear scale. But maybe in another PR, evenif it simple.

**Comment by Eronne** [comment]
The issue related for dataset like `dlk_jules_pda` is now resolved!

**Comment by Eronne** [comment]
> > @romone22 tell me if percents values for `v-progress-linear` are well defined in this PR :)
> 
> @Eronne, the v-progress-linear seems Ok. I'm just wondering if we do not have to use a loggarythmic scale in place of a linear scale. But maybe in another PR, evenif it simple.

Maybe we can use this component? => https://vuetifyjs.com/fr-FR/components/sparklines
Or there is specific needs?

**Pull request merged**
