### PR TITLE
Table to Storage configuration view

### PR DESCRIPTION
**Pull request by Eronne**

### CODE REVIEW

**Comment by Eronne** [comment]
Refactored & splitted components into generic ones to use mixins to generate configuration overview just with data.
➡️TODO: Update firebase request to get real data & update `configuration-overview` components for `gbq-to-gcs-configuration-item`.

**Comment by Eronne** [comment]
Configuration view is available, has to do some refactoring before requesting a review.

**Comment by Eronne** [comment]
Completed table-to-storage views

**Comment by romone22** [comment]
The Destination Table attributes are not visible : 
Exemple : http://localhost:8080/tabletostorage/conf/Control-pimkie-multi-intentions-IT
"dest_gbq_dataset": "dlk_pim_psa",
"dest_gbq_table": "PM_Exported_Stories_MultiIntentions_IT_UnExposed",
"dest_gbq_table_suffix": "dag_execution_date",
"dest_gcp_project_id": "fd-io-dlk-pimkie",

**Comment by romone22** [comment]
The Header is not well set : 
The Configuration Tab must be activated and not the Runs Tab
When you click on Configurations Tab, you arrive on the GBQ to GCS view
Jarvis_Studio

**Comment by Eronne** [comment]
@romone22 is ‘copy_table’ set to true?

As specified in #17 
> IF copy_table == true, add extra parameters
*ParametersTable : Destination Table - The Destination Table where the dataset will be keeped

**Comment by romone22** [comment]
Some attributes have default value as "Delete Destination Storage Content:"
When the attribute is not available, set to the default value with grey color to show it's the default value. 
The default values are available in the documentation. 
Exemple of a default value. 
Jarvis_Studio

**Comment by romone22** [comment]
> @romone22 is ‘copy_table’ set to true?
> 
> As specified in #17
> 
> > IF copy_table == true, add extra parameters
> > *ParametersTable : Destination Table - The Destination Table where the dataset will be keeped

 "copy_table": false,
 "delete_dest_bucket_content": true

**Comment by Eronne** [comment]
> > @romone22 is ‘copy_table’ set to true?
> > As specified in #17
> > > IF copy_table == true, add extra parameters
> > > *ParametersTable : Destination Table - The Destination Table where the dataset will be keeped
> 
> "copy_table": false,
> "delete_dest_bucket_content": true

So with copy_table set to ‘false’ we also have to show destination table ?

**Comment by romone22** [comment]
Agg the Created / Updated block to the configuration View as in the other object view
Jarvis_Studio

**Comment by romone22** [comment]
> > > @romone22 is ‘copy_table’ set to true?
> > > As specified in #17
> > > > IF copy_table == true, add extra parameters
> > > > *ParametersTable : Destination Table - The Destination Table where the dataset will be keeped
> > 
> > 
> > "copy_table": false,
> > "delete_dest_bucket_content": true
> 
> So with copy_table set to ‘false’ we also have to show destination table ?
No, when copy_table is false, there is no destination  table

**Comment by romone22** [comment]
Add a link to view in a nodal window the SQL Source used to generate the dataset to export.
The text of the link is the name of the configuration or maybe just a button "View SQL"
Jarvis_Studio
It's a example from Tables to Tables. Maybe, you can reuse the function that unbinaryze the SQL. 
Jarvis_Studio

**Comment by Eronne** [comment]
> The Header is not well set :
> The Configuration Tab must be activated and not the Runs Tab
> When you click on Configurations Tab, you arrive on the GBQ to GCS view
> Jarvis_Studio

For this behavior, it is common to all data-workflows pages and it can be fixed in an other PR dedicated to this issue (we probably has to use a layout)

**Pull request merged**
